import { canonicalHash } from '../canonical.js';
import type { ApprovedRegulationSource } from './types.js';

const STANDARD_CORRIDORS = [
  'PL-IN-INWARD', 'PL-GB-OUTWARD', 'PL-DE-OUTWARD',
  'IN-PL-OUTWARD', 'IN-GB-OUTWARD', 'IN-DE-OUTWARD',
  'GB-PL-OUTWARD', 'GB-IN-INWARD', 'GB-DE-OUTWARD',
  'DE-PL-OUTWARD', 'DE-IN-INWARD', 'DE-GB-OUTWARD',
] as const;
const INDIA_INWARD_CORRIDORS = ['PL-IN-INWARD', 'GB-IN-INWARD', 'DE-IN-INWARD'] as const;
const INDIA_OUTWARD_CORRIDORS = ['IN-PL-OUTWARD', 'IN-GB-OUTWARD', 'IN-DE-OUTWARD'] as const;
const INDIA_ALL_CORRIDORS = [...INDIA_INWARD_CORRIDORS, ...INDIA_OUTWARD_CORRIDORS] as const;
const UK_CORRIDORS = ['PL-GB-OUTWARD', 'IN-GB-OUTWARD', 'DE-GB-OUTWARD', 'GB-PL-OUTWARD', 'GB-IN-INWARD', 'GB-DE-OUTWARD'] as const;
const EU_MEMBER_CORRIDORS = STANDARD_CORRIDORS.filter((book) => /^(PL|DE)-|-(PL|DE)-/u.test(book));
const RUSSIA_CORRIDORS = [
  'PL-RU-OUTWARD', 'IN-RU-OUTWARD', 'GB-RU-OUTWARD', 'DE-RU-OUTWARD',
  'RU-PL-OUTWARD', 'RU-IN-INWARD', 'RU-GB-OUTWARD', 'RU-DE-OUTWARD',
] as const;
const DPRK_CORRIDORS = [
  'PL-KP-OUTWARD', 'IN-KP-OUTWARD', 'GB-KP-OUTWARD', 'DE-KP-OUTWARD', 'RU-KP-OUTWARD',
  'KP-PL-OUTWARD', 'KP-IN-INWARD', 'KP-GB-OUTWARD', 'KP-DE-OUTWARD', 'KP-RU-OUTWARD',
] as const;

/**
 * Human-reviewed, compact extracts from official primary sources.
 *
 * These records are intentionally source controlled. Refresh observations do
 * not update this array and therefore cannot change a compliance outcome.
 */
export const APPROVED_REGULATION_SOURCES: readonly ApprovedRegulationSource[] = [
  {
    id: 'rbi-pa-cb-2023-10-31',
    title: 'Regulation of Payment Aggregator – Cross Border (PA-CB)',
    authority: 'RBI',
    jurisdiction: 'IN',
    sourceUri: 'https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12561&Mode=0',
    officialDocumentDate: '2023-10-31',
    approvedVersion: 'RBI-2023-24-80',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.rbi.org.in', 'rbi.org.in'],
    approvedMarkers: [
      'Regulation of Payment Aggregator – Cross Border (PA - Cross Border)',
      'CO.DPSS.POLC.No.S-786/02-14-008/2023-24',
      'In case per unit goods / services imported is more than ₹2,50,000',
      'the maximum value per unit of goods / services sold / purchased shall be ₹25,00,000',
      'Separate collection accounts – ICA and ECA – shall be maintained',
    ],
    chunks: [
      {
        id: 'rbi-pa-cb-4.4',
        section: 'Annex paragraph 4.4',
        summary: 'For PA-CB import transactions above ₹2.5 lakh per unit, the PA-CB must also perform buyer due diligence.',
        quote: 'the concerned PA-CB shall undertake due diligence of buyer also',
        tags: ['india', 'import', 'outward', 'buyer', 'due diligence', 'kyc', 'threshold'],
        appliesToBooks: INDIA_OUTWARD_CORRIDORS,
      },
      {
        id: 'rbi-pa-cb-4.3',
        section: 'Annex paragraphs 4.3–4.4',
        summary: 'Import PA-CBs must perform merchant due diligence, screen prohibited or restricted trade, and apply buyer due diligence above the stated threshold.',
        quote: 'they do not facilitate payment transactions for import of any restricted / prohibited goods and services',
        tags: ['india', 'import', 'outward', 'merchant', 'due diligence', 'prohibited', 'purpose'],
        appliesToBooks: INDIA_OUTWARD_CORRIDORS,
      },
      {
        id: 'rbi-pa-cb-5.3-5.4',
        section: 'Annex paragraphs 5.3–5.4',
        summary: 'Export PA-CBs must screen prohibited or restricted trade, perform merchant due diligence, and settle proceeds only to the onboarded merchant account.',
        quote: 'proceeds from ECA shall be settled only in the account of such merchant',
        tags: ['india', 'export', 'inward', 'merchant', 'due diligence', 'prohibited', 'purpose'],
        appliesToBooks: INDIA_INWARD_CORRIDORS,
      },
      {
        id: 'rbi-pa-cb-6.1',
        section: 'Annex paragraph 6.1',
        summary: 'A PA-CB handling imports and exports must keep the import and export collection accounts separate.',
        quote: 'Separate collection accounts – ICA and ECA – shall be maintained',
        tags: ['india', 'inward', 'outward', 'ledger', 'separation', 'ica', 'eca'],
        appliesToBooks: INDIA_ALL_CORRIDORS,
      },
      {
        id: 'rbi-pa-cb-8.2',
        section: 'Annex paragraph 8.2',
        summary: 'A PA-CB may process at most ₹25 lakh per unit of goods or services.',
        quote: 'the maximum value per unit of goods / services sold / purchased shall be ₹25,00,000',
        tags: ['india', 'import', 'export', 'cap', 'threshold', 'goods', 'services'],
        appliesToBooks: INDIA_ALL_CORRIDORS,
      },
    ],
  },
  {
    id: 'rbi-import-goods-services-2024-08-29',
    title: 'Master Direction – Import of Goods and Services',
    authority: 'RBI',
    jurisdiction: 'IN',
    sourceUri: 'https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10201',
    officialDocumentDate: '2024-08-29',
    approvedVersion: 'RBI-FED-2016-17-12@2024-08-29',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.rbi.org.in', 'rbi.org.in'],
    approvedMarkers: [
      'Master Direction – Import of Goods and Services',
      'Updated as on August 29, 2024',
      'Import of Goods and Services into India is being allowed in terms of Section 5',
    ],
    chunks: [{
      id: 'rbi-import-introduction',
      section: 'Introduction',
      summary: 'Indian import payments operate under FEMA current-account rules and through Authorised Dealer Category-I banks.',
      quote: 'Import of Goods and Services into India is being allowed in terms of Section 5',
      tags: ['india', 'import', 'outward', 'fema', 'authorised dealer', 'supplier'],
      appliesToBooks: INDIA_OUTWARD_CORRIDORS,
    }],
  },
  {
    id: 'rbi-other-remittance-2024-09-06',
    title: 'Master Direction – Other Remittance Facilities',
    authority: 'RBI',
    jurisdiction: 'IN',
    sourceUri: 'https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10193',
    officialDocumentDate: '2024-09-06',
    approvedVersion: 'RBI-FED-MD-8-2015-16@2024-09-06',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.rbi.org.in', 'rbi.org.in'],
    approvedMarkers: [
      'Master Direction - Other Remittance Facilities',
      'Updated as on September 06, 2024',
      'For payments other than imports and remittances covering intermediary trade transactions',
    ],
    chunks: [{
      id: 'rbi-other-remittance-6.4-6.5',
      section: 'Paragraphs 6.4–6.5',
      summary: 'Form A2 applies to covered cross-border remittances, but paragraph 6.4 expressly distinguishes imports and intermediary trade.',
      quote: 'For payments other than imports and remittances covering intermediary trade transactions',
      tags: ['india', 'outward', 'form a2', 'fema', 'remittance', 'documents'],
      appliesToBooks: INDIA_OUTWARD_CORRIDORS,
    }],
  },
  {
    id: 'india-income-tax-form-15ca',
    title: 'Form 15CA FAQs',
    authority: 'INDIA_INCOME_TAX',
    jurisdiction: 'IN',
    sourceUri: 'https://www.incometax.gov.in/iec/foportal/help/statutory-forms/popular-forms/form-15ca-faq',
    approvedVersion: 'INCOME-TAX-FORM-15CA-OBSERVED-2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.incometax.gov.in', 'incometax.gov.in'],
    approvedMarkers: [
      'Form 15CA FAQs',
      'before remitting the payment',
      'In certain cases, a Certificate from Chartered Accountant in form 15CB is required',
    ],
    chunks: [{
      id: 'income-tax-15ca-purpose',
      section: 'FAQs 1–4',
      summary: 'Form 15CA reports qualifying payments to a non-resident or foreign company; some taxable remittances require a Form 15CB accountant certificate.',
      quote: 'A person responsible for making such remittance has to submit the form 15CA',
      tags: ['india', 'outward', 'tax', 'form 15ca', 'form 15cb', 'non-resident'],
      appliesToBooks: INDIA_OUTWARD_CORRIDORS,
    }],
  },
  {
    id: 'uk-financial-sanctions-guidance',
    title: 'UK financial sanctions general guidance',
    authority: 'UK_GOVERNMENT',
    jurisdiction: 'GB',
    sourceUri: 'https://www.gov.uk/government/publications/financial-sanctions-general-guidance',
    officialDocumentDate: '2026-05-12',
    approvedVersion: 'UK-OFSI-GENERAL-GUIDANCE@2026-05-12',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.gov.uk', 'gov.uk'],
    approvedMarkers: [
      'Financial sanctions general guidance',
      'Ownership and control',
      'The UK Sanctions List is now the only source for all UK sanctions designations',
    ],
    chunks: [{
      id: 'uk-ofsi-screening-scope',
      section: 'General guidance: scope, ownership and control',
      summary: 'UK sanctions screening must cover designated parties and ownership or control; the UK Sanctions List is the current designation source.',
      quote: 'The UK Sanctions List is now the only source for all UK sanctions designations',
      tags: ['united kingdom', 'sanctions', 'ownership', 'control', 'supplier', 'screening'],
      appliesToBooks: UK_CORRIDORS,
    }],
  },
  {
    id: 'uk-payment-services-conduct',
    title: 'Electronic money and payment service providers: conduct of business requirements',
    authority: 'UK_FCA',
    jurisdiction: 'GB',
    sourceUri: 'https://www.fca.org.uk/firms/payment-service-providers-conduct-business-requirements',
    officialDocumentDate: '2026-09-04',
    approvedVersion: 'UK-FCA-PSR-CONDUCT@2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.fca.org.uk', 'fca.org.uk'],
    approvedMarkers: [
      'Electronic money and payment service providers: conduct of business requirements',
      'Payment Services Regulations 2017',
      'post contract information, such as amount and currency of payment transactions',
    ],
    chunks: [{
      id: 'uk-psr-payment-information',
      section: 'PSRs conduct requirements: information requirements',
      summary: 'A UK payment service provider must provide applicable transaction information, including amount and currency, under the Payment Services Regulations 2017 conduct requirements.',
      quote: 'post contract information, such as amount and currency of payment transactions',
      tags: ['united kingdom', 'payment service provider', 'transaction reference', 'amount', 'currency', 'fees'],
      appliesToBooks: UK_CORRIDORS,
    }],
  },
  {
    id: 'uk-vat-export-goods',
    title: 'Exports, sending goods abroad and charging VAT',
    authority: 'UK_GOVERNMENT',
    jurisdiction: 'GB',
    sourceUri: 'https://www.gov.uk/guidance/vat-exports-dispatches-and-supplying-goods-abroad',
    officialDocumentDate: '2020-12-31',
    approvedVersion: 'UK-HMRC-VAT-EXPORT-GOODS@2020-12-31',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.gov.uk', 'gov.uk'],
    approvedMarkers: [
      'Exports, sending goods abroad and charging VAT',
      'You can zero rate the sale, as long as you get and keep evidence of the export',
      'You must keep evidence for 6 years',
    ],
    chunks: [{
      id: 'uk-vat-export-evidence',
      section: 'VAT on exports; proof and record keeping',
      summary: 'A Great Britain goods exporter may zero-rate an export only when the conditions are met and export evidence is obtained and retained; invoices, sales records and export evidence are retained.',
      quote: 'You can zero rate the sale, as long as you get and keep evidence of the export',
      tags: ['united kingdom', 'goods', 'export', 'vat', 'proof of export', 'invoice', 'records'],
      appliesToBooks: UK_CORRIDORS,
    }],
  },
  {
    id: 'uk-export-declaration',
    title: 'Make and manage an export declaration online',
    authority: 'UK_GOVERNMENT',
    jurisdiction: 'GB',
    sourceUri: 'https://www.gov.uk/guidance/make-and-manage-an-export-declaration-online',
    officialDocumentDate: '2024-03-04',
    approvedVersion: 'UK-HMRC-EXPORT-DECLARATION@2024-03-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.gov.uk', 'gov.uk'],
    approvedMarkers: [
      'Make and manage an export declaration online',
      'have the right commodity code for the goods',
      'have invoice and packing list references',
    ],
    chunks: [{
      id: 'uk-export-declaration-evidence',
      section: 'Before you start; after you have declared',
      summary: 'A Great Britain goods export declaration uses the parties’ EORI details, commodity code, value, packaging, destination and transport data, with invoice and packing-list references and any required export licence or certificate.',
      quote: 'have invoice and packing list references',
      tags: ['united kingdom', 'goods', 'export declaration', 'eori', 'commodity code', 'invoice', 'packing list'],
      appliesToBooks: UK_CORRIDORS,
    }],
  },
  {
    id: 'uk-vat-export-services',
    title: 'Place of supply of services (VAT Notice 741A)',
    authority: 'UK_GOVERNMENT',
    jurisdiction: 'GB',
    sourceUri: 'https://www.gov.uk/guidance/vat-place-of-supply-of-services-notice-741a',
    officialDocumentDate: '2022-09-29',
    approvedVersion: 'UK-HMRC-VAT-NOTICE-741A@2022-09-29',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.gov.uk', 'gov.uk'],
    approvedMarkers: [
      'Place of supply of services (VAT Notice 741A)',
      'no UK VAT is chargeable where the place of supply is outside the UK',
      'You’ll always need to consider all the facts',
    ],
    chunks: [{
      id: 'uk-services-place-of-supply',
      section: 'Overview and general rule',
      summary: 'UK service suppliers must determine the place of supply from the full facts; where that place is outside the UK, UK VAT is not charged, subject to service-specific rules.',
      quote: 'no UK VAT is chargeable where the place of supply is outside the UK',
      tags: ['united kingdom', 'services', 'export', 'vat', 'place of supply', 'business customer'],
      appliesToBooks: UK_CORRIDORS,
    }],
  },
  {
    id: 'uk-invoice-requirements',
    title: 'Invoices - what they must include',
    authority: 'UK_GOVERNMENT',
    jurisdiction: 'GB',
    sourceUri: 'https://www.gov.uk/invoicing-and-taking-payment-from-customers/invoices-what-they-must-include',
    approvedVersion: 'UK-GOV-INVOICE-CONTENTS@2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.gov.uk', 'gov.uk'],
    approvedMarkers: [
      'Invoices - what they must include',
      'a unique identification number',
      'a clear description of what you’re charging for',
    ],
    chunks: [{
      id: 'uk-invoice-contents',
      section: 'Invoice contents',
      summary: 'UK invoices identify the invoice, supplier and customer and state the supply description, dates, amounts, applicable VAT and total owed.',
      quote: 'a clear description of what you’re charging for',
      tags: ['united kingdom', 'invoice', 'supplier', 'customer', 'description', 'date', 'amount'],
      appliesToBooks: UK_CORRIDORS,
    }],
  },
  {
    id: 'germany-payment-services-supervision',
    title: 'BaFin: authorisation for payment-services activity',
    authority: 'GERMAN_BAFIN',
    jurisdiction: 'DE',
    sourceUri: 'https://www.bafin.de/ref/19629832',
    officialDocumentDate: '2022-09-01',
    approvedVersion: 'BAFIN-ZAG-AUTHORISATION@2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.bafin.de', 'bafin.de'],
    approvedMarkers: [
      'Benötige ich für meine Tätigkeit eine Erlaubnis der BaFin',
      'Zahlungsdiensteaufsichtsgesetz',
      'technische Dienstleistungen',
    ],
    chunks: [{
      id: 'bafin-zag-provider-boundary',
      section: 'Payment-services authorisation boundary',
      summary: 'A provider that receives customer funds or issues monetary value may require German payment-services or e-money authorisation; a technical-service role depends on the actual contractual and funds-flow design.',
      quote: 'Ob Sie eine Erlaubnis benötigen, hängt davon ab, wie die Zahlungsabwicklung gestaltet ist',
      tags: ['germany', 'bafin', 'payment services', 'authorisation', 'technical service provider', 'zag'],
      appliesToBooks: [...EU_MEMBER_CORRIDORS, 'DE-RU-OUTWARD', 'RU-DE-OUTWARD'],
    }],
  },
  {
    id: 'russia-cross-border-transfers-2026',
    title: 'Bank of Russia: cross-border transfers and payments',
    authority: 'RUSSIA_CENTRAL_BANK',
    jurisdiction: 'RU',
    sourceUri: 'https://www.cbr.ru/faq/w_fin_sector/Transgranichnie_perevodi/',
    officialDocumentDate: '2026-06-01',
    approvedVersion: 'CBR-CROSS-BORDER-TRANSFERS@2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.cbr.ru', 'cbr.ru'],
    approvedMarkers: [
      'Трансграничные переводы и платежи',
      'Переводы за границу',
      'недружественных стран',
    ],
    chunks: [{
      id: 'cbr-cross-border-current-controls',
      section: 'Current cross-border transfer controls',
      summary: 'Russian cross-border transfer permissions and restrictions depend on residency, counterparty status, payment purpose and temporary measures, so Anchor requires a current human and provider review.',
      quote: 'Трансграничные переводы и платежи',
      tags: ['russia', 'cross-border', 'currency control', 'residency', 'temporary restrictions', 'payment purpose'],
      appliesToBooks: RUSSIA_CORRIDORS,
    }],
  },
  {
    id: 'eu-transfer-of-funds-2023-1113',
    title: 'Regulation (EU) 2023/1113 on information accompanying transfers of funds and certain crypto-assets',
    authority: 'EU',
    jurisdiction: 'EU',
    sourceUri: 'https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A32023R1113',
    refreshUri: 'https://publications.europa.eu/resource/cellar/48eca7a6-0660-11ee-b12e-01aa75ed71a1/rdf/object/full',
    officialDocumentDate: '2023-05-31',
    approvedVersion: 'CELEX-32023R1113@observed-2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['eur-lex.europa.eu', 'publications.europa.eu'],
    approvedMarkers: [
      'http://publications.europa.eu/resource/celex/32023R1113',
      'http://publications.europa.eu/resource/eli/reg/2023/1113/oj',
      'http://publications.europa.eu/resource/consolidation/2023R1113%2F20230609',
    ],
    chunks: [
      {
        id: 'eu-tfr-article-4',
        section: 'Article 4',
        summary: 'An EU payer PSP must ensure a transfer carries specified payer and payee information or a traceable unique transaction identifier.',
        quote: 'Information accompanying transfers of funds',
        tags: ['eu', 'poland', 'payer', 'payee', 'payment service provider', 'traceability'],
        appliesToBooks: [...EU_MEMBER_CORRIDORS, 'PL-RU-OUTWARD', 'DE-RU-OUTWARD', 'PL-KP-OUTWARD', 'DE-KP-OUTWARD'],
      },
      {
        id: 'eu-tfr-articles-25-26',
        section: 'Articles 25–26',
        summary: 'Transfer information is subject to GDPR purpose limitation and generally a five-year regulatory retention period.',
        quote: 'Personal data shall be processed ... only for the purposes of the prevention of money laundering',
        tags: ['eu', 'poland', 'privacy', 'gdpr', 'retention', 'aml'],
        appliesToBooks: [...EU_MEMBER_CORRIDORS, 'PL-RU-OUTWARD', 'DE-RU-OUTWARD', 'PL-KP-OUTWARD', 'DE-KP-OUTWARD'],
      },
    ],
  },
  {
    id: 'poland-aml-act-landing-2025-04-17',
    title: 'Polish Ministry of Finance AML/CFT legislation',
    authority: 'POLAND_MINISTRY_OF_FINANCE',
    jurisdiction: 'PL',
    sourceUri: 'https://www.gov.pl/web/finance/legislation-aml-ctf',
    officialDocumentDate: '2025-04-17',
    approvedVersion: 'PL-MOF-AML-LEGISLATION@2025-04-17',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.gov.pl', 'gov.pl'],
    approvedMarkers: [
      'Act of 1 March 2018 on counteracting money laundering and financing of terrorism',
      'The only binding text is the Polish text of these documents',
      '17.04.2025',
    ],
    chunks: [{
      id: 'poland-aml-act-status',
      section: 'Legislation notice',
      summary: 'The Polish AML/CFT Act is the national legal baseline; the Ministry warns that its English translation is informational and the Polish text is binding.',
      quote: 'The only binding text is the Polish text of these documents',
      tags: ['poland', 'aml', 'cft', 'customer due diligence', 'binding language'],
      appliesToBooks: [...EU_MEMBER_CORRIDORS, 'PL-RU-OUTWARD', 'DE-RU-OUTWARD', 'PL-KP-OUTWARD', 'DE-KP-OUTWARD'],
    }],
  },
  {
    id: 'poland-cesop-cross-border-payments',
    title: 'Poland: Payment Services Providers – cross-border transaction records',
    authority: 'POLAND_MINISTRY_OF_FINANCE',
    jurisdiction: 'PL',
    sourceUri: 'https://www.gov.pl/web/national-revenue-administration/payment-services-providers',
    approvedVersion: 'PL-CESOP-PSP-2024',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.gov.pl', 'gov.pl'],
    approvedMarkers: [
      'From 1 January 2024, Payment Service Providers have new obligations',
      'more than 25 payments to the same payment recipient',
      'The period for which the records are kept by payment service providers is 3 years',
    ],
    chunks: [{
      id: 'poland-cesop-records',
      section: 'Obligation to keep records',
      summary: 'Polish CESOP reporting may apply when a PSP makes more than 25 cross-border payments to the same recipient in a calendar quarter; records are retained for three years.',
      quote: 'more than 25 payments to the same payment recipient in a given Member State during a calendar quarter',
      tags: ['poland', 'cesop', 'cross-border', 'records', 'reporting', 'payment service provider'],
      appliesToBooks: [...EU_MEMBER_CORRIDORS, 'PL-RU-OUTWARD', 'DE-RU-OUTWARD', 'PL-KP-OUTWARD', 'DE-KP-OUTWARD'],
    }],
  },
  {
    id: 'eu-vat-place-of-supply',
    title: 'EU VAT place of taxation for services',
    authority: 'EU',
    jurisdiction: 'EU',
    sourceUri: 'https://taxation-customs.ec.europa.eu/where-tax_en',
    approvedVersion: 'EU-VAT-ARTICLES-44-45@2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['taxation-customs.ec.europa.eu'],
    approvedMarkers: ['Place of taxation', 'B2B supplies', 'Article 44 VAT Directive'],
    chunks: [{
      id: 'eu-vat-b2b-place',
      section: 'B2B services — Article 44',
      summary: 'The default place of taxation for B2B services is where the business customer is established, subject to service-specific exceptions.',
      quote: 'the place of taxation is the place where the customer is established',
      tags: ['eu', 'germany', 'poland', 'b2b', 'services', 'vat', 'place of supply'],
      appliesToBooks: EU_MEMBER_CORRIDORS,
    }],
  },
  {
    id: 'eu-vat-invoicing',
    title: 'EU VAT invoicing rules',
    authority: 'EU',
    jurisdiction: 'EU',
    sourceUri: 'https://taxation-customs.ec.europa.eu/taxation/vat/vat-businesses/invoicing_en',
    approvedVersion: 'EU-VAT-INVOICING@2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['taxation-customs.ec.europa.eu'],
    approvedMarkers: ['VAT Invoicing', 'When is an invoice compulsory?', 'reverse charge'],
    chunks: [{
      id: 'eu-vat-reverse-charge-invoice',
      section: 'VAT invoice contents',
      summary: 'Most B2B supplies require an invoice; where the customer is liable, the invoice carries reverse-charge wording.',
      quote: 'the words ‘reverse charge’',
      tags: ['eu', 'germany', 'poland', 'invoice', 'reverse charge', 'vat'],
      appliesToBooks: EU_MEMBER_CORRIDORS,
    }],
  },
  {
    id: 'eu-financial-sanctions-overview',
    title: 'EU sanctions and related resources',
    authority: 'EU',
    jurisdiction: 'EU',
    sourceUri: 'https://finance.ec.europa.eu/eu-and-world/sanctions-restrictive-measures/overview-sanctions-and-related-resources_en',
    approvedVersion: 'EU-FINANCIAL-SANCTIONS@2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['finance.ec.europa.eu'],
    approvedMarkers: ['Overview of sanctions and related resources', 'consolidated list', 'EU sanctions map'],
    chunks: [{
      id: 'eu-sanctions-listed-parties',
      section: 'Consolidated list and sanctions map',
      summary: 'EU measures can target specific governments, entities, groups and individuals, so party and ownership screening is distinct from a country label.',
      quote: 'EU sanctions map',
      tags: ['eu', 'poland', 'russia', 'sanctions', 'listed party', 'beneficial owner', 'bank'],
      appliesToBooks: [...EU_MEMBER_CORRIDORS, ...RUSSIA_CORRIDORS, 'PL-KP-OUTWARD', 'DE-KP-OUTWARD'],
    }],
  },
  {
    id: 'eu-dprk-financial-restrictions',
    title: 'EU sanctions against North Korea',
    authority: 'EU_COUNCIL',
    jurisdiction: 'EU',
    sourceUri: 'https://www.consilium.europa.eu/en/policies/sanctions-against-north-korea/timeline-eu-sanctions-against-north-korea/',
    approvedVersion: 'EU-DPRK-SANCTIONS@2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['www.consilium.europa.eu', 'consilium.europa.eu'],
    approvedMarkers: ['EU sanctions against North Korea', 'prohibition of transfers of funds', 'authorised in advance'],
    chunks: [{
      id: 'eu-dprk-fund-transfer',
      section: 'Financial-sector restrictions',
      summary: 'EU measures prohibit transfers of funds to and from the DPRK except for predefined purposes authorized in advance.',
      quote: 'prohibition of transfers of funds to and from the DPRK',
      tags: ['eu', 'poland', 'dprk', 'north korea', 'sanctions', 'fund transfer', 'authorization'],
      appliesToBooks: ['PL-KP-OUTWARD'],
    }],
  },
  {
    id: 'un-security-council-dprk-1718',
    title: 'Security Council Committee established pursuant to resolution 1718 (2006)',
    authority: 'UN_SECURITY_COUNCIL',
    jurisdiction: 'UN',
    sourceUri: 'https://main.un.org/securitycouncil/en/sanctions/1718',
    approvedVersion: 'UNSC-DPRK-1718@OBSERVED-2026-09-04',
    approvedAt: '2026-09-04',
    allowedHosts: ['main.un.org'],
    approvedMarkers: [
      'Security Council Committee established pursuant to resolution 1718 (2006)',
      'All Member States are required to freeze the assets, funds, and economic resources',
      'All Member States are required to prevent the provision of financial services',
    ],
    chunks: [{
      id: 'un-dprk-assets-financial-measures',
      section: 'Sanction measures: assets freeze and financial measures',
      summary: 'UN members must implement DPRK asset-freeze and financial measures, including controls against financial services that could support prohibited programmes or sanctions evasion. Because Anchor has no designation, licensing or exemption workflow, its product policy blocks every DPRK-involved route.',
      quote: 'All Member States are required to prevent the provision of financial services',
      tags: ['un', 'dprk', 'north korea', 'assets freeze', 'financial services', 'member states', 'sanctions'],
      appliesToBooks: DPRK_CORRIDORS,
    }],
  },
] as const;

export function approvedCorpusHash(sources: readonly ApprovedRegulationSource[] = APPROVED_REGULATION_SOURCES): string {
  return canonicalHash(sources.map((source) => ({
    id: source.id,
    approvedVersion: source.approvedVersion,
    chunks: source.chunks,
  })));
}
