if('scrollRestoration' in history)history.scrollRestoration='manual';if(location.hash){history.replaceState(null,'',location.pathname+location.search)}scrollTo(0,0);addEventListener('load',()=>scrollTo(0,0));
const canvas=document.querySelector('#globeCanvas'),ctx=canvas.getContext('2d');let dots=[];
function resize(){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);dots=Array.from({length:620},()=>{const z=Math.random()*2-1,t=Math.random()*Math.PI*2,q=Math.sqrt(1-z*z);return{x:q*Math.cos(t),y:z,z:q*Math.sin(t),s:Math.random()*.9+.25}})}
const cardColors=['#7a35dc','#dc438d','#ef6877','#3e8bb7'],cardSymbols=['₹','€','$','zł'];
function paymentCard(x,y,w,h,color,symbol,angle){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle='#07100d';ctx.fillRect(-w/2+6,-h/2+7,w,h);ctx.fillStyle=color;ctx.fillRect(-w/2,-h/2,w,h);ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.strokeRect(-w/2,-h/2,w,h);ctx.fillStyle='#fff';ctx.font=`700 ${Math.max(11,w*.27)}px ${getComputedStyle(document.documentElement).getPropertyValue('--mono')}`;ctx.fillText(symbol,-w*.33,-h*.18);ctx.globalAlpha=.65;ctx.fillStyle='#fff';ctx.fillRect(-w*.32,h*.2,w*.42,2);ctx.fillRect(-w*.32,h*.3,w*.2,2);ctx.restore();ctx.globalAlpha=1}
function globe(time=0){const w=canvas.clientWidth,h=canvas.clientHeight,cx=w*.5,cy=h*.69,r=Math.min(w*.34,h*.45),spin=time*.00007;ctx.clearRect(0,0,w,h);const g=ctx.createRadialGradient(cx,cy,0,cx,cy,r*1.35);g.addColorStop(0,'rgba(181,255,74,.18)');g.addColorStop(1,'rgba(181,255,74,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(181,255,74,.28)';ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();for(let i=1;i<7;i++){ctx.beginPath();ctx.ellipse(cx,cy,r,r*i/7,0,0,Math.PI*2);ctx.stroke()}for(let i=0;i<10;i++){ctx.beginPath();ctx.ellipse(cx,cy,r*Math.abs(Math.cos(i*Math.PI/10)),r,0,0,Math.PI*2);ctx.stroke()}dots.forEach(p=>{const x=p.x*Math.cos(spin)-p.z*Math.sin(spin),z=p.x*Math.sin(spin)+p.z*Math.cos(spin);if(z<-.08)return;ctx.globalAlpha=.08+(z+1)*.17;ctx.fillStyle='#d9ff45';ctx.fillRect(cx+x*r,cy+p.y*r,p.s,p.s)});ctx.globalAlpha=1;ctx.setLineDash([4,7]);ctx.lineDashOffset=-time*.018;ctx.strokeStyle='#754bd2';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w*.06,h*.78);ctx.quadraticCurveTo(cx,cy-r*.3,w*.94,h*.78);ctx.stroke();ctx.setLineDash([]);
  const count=w<650?10:18;for(let side=0;side<2;side++)for(let i=0;i<count;i++){const phase=((time*.00007+i/count)+(side?0:.5))%1,ease=phase<.5?phase*2:(1-phase)*2,from=side?-w*.08:w*1.08,to=cx+(side?48:-48),x=from+(to-from)*ease,y=h*.73-Math.sin(ease*Math.PI)*r*.2+Math.sin(i*1.9)*34,scale=.54+ease*.62,cw=42*scale,ch=78*scale,ang=(side?-1:1)*(.19-Math.sin(i)*.08);paymentCard(x,y,cw,ch,cardColors[i%cardColors.length],cardSymbols[(i+side)%cardSymbols.length],ang)}
  ctx.fillStyle='#d9ff45';ctx.shadowColor='#d9ff45';ctx.shadowBlur=18;ctx.fillRect(cx-9,cy-9,18,18);ctx.shadowBlur=0;ctx.strokeStyle='#8250df';ctx.lineWidth=2;ctx.strokeRect(cx-24,cy-24,48,48);ctx.strokeRect(cx-39,cy-39,78,78);requestAnimationFrame(globe)}
resize();addEventListener('resize',resize);requestAnimationFrame(globe);

const arcade=document.querySelector('#arcade'),kick=document.querySelector('#kickButton');kick.addEventListener('click',()=>{arcade.classList.remove('kicked');void arcade.offsetWidth;arcade.classList.add('kicked');document.querySelector('#kickStatus').textContent='DIRECT ROUTE OPEN · MIDDLE MAN REMOVED ✓';document.querySelector('#feeScore').textContent='FEES: 1 CLEAR QUOTE';kick.querySelector('span').textContent='DONE'});

const journeyLevels=['LEVEL 1 · AGREEMENT','LEVEL 2 · FUNDING','LEVEL 3 · WORK PROOF','LEVEL 4 · APPROVAL','LEVEL 5 · PAYOUT'];
const journeyStates=['CONTRACT LOCKED · PRESS GO','ESCROW FUNDED · PRESS GO','WORK PROOF RECORDED · PRESS GO','MILESTONE APPROVED · PRESS GO','PAYMENT COMPLETE · PLAY AGAIN'];
const journeyCopy=[
 ['AGREEMENT / 01','ONE CONTRACT. TWO CLEAR YESSES.','The company and freelancer verify their identities and approve the same scope, milestone, deadline and payout.'],
 ['FUNDING / 02','LOCAL MONEY ENTERS ESCROW.','The company pays in PLN. The origin provider locks the quoted settlement value while both users stay entirely in fiat.'],
 ['WORK PROOF / 03','THE FILE STAYS PRIVATE.','The freelancer uploads the deliverable. Anchor records only its secure fingerprint and version on the work ledger.'],
 ['APPROVAL / 04','APPROVAL UNLOCKS RELEASE.','The company reviews the real file and approves the milestone. That verified decision authorizes one escrow release.'],
 ['PAYOUT / 05','RUPEES ARRIVE LOCALLY.','Settlement completes between providers and the freelancer receives INR with a complete, auditable payment timeline.']
];
let journeyLevel=-1,journeyTimer=null;const slideTrack=document.querySelector('#slideTrack'),goButton=document.querySelector('#goButton'),levelDots=[...document.querySelectorAll('#levelDots i')];
function showJourneyLevel(n){journeyLevel=n;const copy=journeyCopy[n];slideTrack.style.transform=`translateX(-${n*100}%)`;document.querySelector('#levelName').textContent=journeyLevels[n];document.querySelector('#journeyStatus').textContent=n===4?'PAYMENT COMPLETE':'JOURNEY RUNNING';document.querySelector('#healthBar').style.width=`${20+n*20}%`;document.querySelector('#powerBar').style.width=`${20+n*20}%`;document.querySelector('#journeyCopyStep').textContent=copy[0];document.querySelector('#journeyCopyTitle').textContent=copy[1];document.querySelector('#journeyCopyText').textContent=copy[2];levelDots.forEach((dot,i)=>dot.classList.toggle('active',i<=n))}
function playJourney(){if(journeyTimer)return;goButton.classList.remove('complete');goButton.classList.add('playing');goButton.querySelector('span').textContent='RUN';showJourneyLevel(0);journeyTimer=setInterval(()=>{if(journeyLevel<4){showJourneyLevel(journeyLevel+1);return}clearInterval(journeyTimer);journeyTimer=null;goButton.classList.remove('playing');goButton.classList.add('complete');goButton.querySelector('span').textContent='AGAIN';document.querySelector('#journeyStatus').textContent='MISSION COMPLETE'},2300)}
goButton.addEventListener('click',playJourney);

const steps=[
 {label:'STEP 01 · AGREEMENT',title:'One contract.<br>Two clear yeses.',copy:'The Polish company and Indian freelancer approve the same scope, milestone and payout terms.',status:'IDENTITIES VERIFIED · TERMS LOCKED',state:'AGREEMENT SIGNED'},
 {label:'STEP 02 · FUNDING',title:'Pay locally.<br>Secure globally.',copy:'The company funds in PLN. A licensed-provider simulation converts the quote and locks settlement funds in escrow.',status:'FX QUOTE LOCKED · ESCROW FUNDED',state:'€4,800 SECURED'},
 {label:'STEP 03 · DELIVERY',title:'Submit the work.<br>Keep it private.',copy:'The freelancer uploads the deliverable privately. Only its cryptographic fingerprint and version are recorded.',status:'FILE PRIVATE · EVIDENCE COMMITTED',state:'WORK HASH VERIFIED'},
 {label:'STEP 04 · APPROVAL',title:'Review the work.<br>Release with proof.',copy:'The company approves the milestone. The evidence decision authorizes a single protected escrow release.',status:'APPROVAL RECORDED · RELEASE PERMITTED',state:'WORK APPROVED'},
 {label:'STEP 05 · PAYOUT',title:'Receive rupees.<br>Not crypto.',copy:'The destination provider completes the off-ramp and credits the freelancer’s simulated INR balance.',status:'SETTLEMENT FINAL · LOCAL CREDIT POSTED',state:'₹433,846 RECEIVED'}
];
const tabs=[...document.querySelectorAll('[data-step]')],track=[...document.querySelectorAll('.receipt-track i')];function setStep(n){const s=steps[n];tabs.forEach((b,i)=>b.classList.toggle('active',i===n));document.querySelector('#stepLabel').textContent=s.label;document.querySelector('#stepTitle').innerHTML=s.title;document.querySelector('#stepCopy').textContent=s.copy;document.querySelector('#stepStatus').textContent=s.status;document.querySelector('#receiptState').textContent=s.state;track.forEach((el,i)=>el.classList.toggle('active',i<=n))}tabs.forEach(b=>b.addEventListener('click',()=>setStep(+b.dataset.step)));

const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const modal=document.querySelector('#demoModal');function openModal(){modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}document.querySelectorAll('[data-open-demo]').forEach(b=>b.addEventListener('click',openModal));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeModal));document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#demoNote').textContent=`${b.dataset.role.toUpperCase()} DEMO SELECTED · WORKSPACE COMING NEXT`;b.parentElement.querySelectorAll('button').forEach(x=>x.style.background=x===b?'#d9ff45':'#fff')}));addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

const selectableRoles=[
 {name:'COMPANY',image:'assets/optiwork-company-pixel.png',alt:'Company representative',copy:'Create contracts, review verified work and fund cross-border payouts in your local currency.',stats:[4,4,3]},
 {name:'FREELANCER',image:'assets/optiwork-freelancer-pixel.png',alt:'Freelancer',copy:'Accept projects, submit private work evidence and receive completed payouts in your local currency.',stats:[3,3,4]}
];
let selectedRole=0;const rolePortrait=document.querySelector('.role-portrait');
function renderSelectedRole(direction=1){const role=selectableRoles[selectedRole],image=document.querySelector('#selectedRoleImage');rolePortrait.classList.add('changing');setTimeout(()=>{image.src=role.image;image.alt=role.alt;document.querySelector('#selectedRoleName').textContent=role.name;document.querySelector('#selectedRoleCopy').textContent=role.copy;document.querySelector('#roleCounter').textContent=`0${selectedRole+1} / 02 · USE ARROWS TO SWITCH`;document.querySelector('#continueRole span').textContent=`CONTINUE AS ${role.name}`;document.querySelectorAll('[data-role-stat]').forEach((row,i)=>row.querySelectorAll('b').forEach((bar,j)=>bar.classList.toggle('on',j<role.stats[i])));rolePortrait.classList.remove('changing')},180)}
function switchSelectedRole(direction){selectedRole=(selectedRole+direction+selectableRoles.length)%selectableRoles.length;renderSelectedRole(direction)}
document.querySelector('#rolePrev').addEventListener('click',()=>switchSelectedRole(-1));document.querySelector('#roleNext').addEventListener('click',()=>switchSelectedRole(1));addEventListener('keydown',e=>{if(!modal.classList.contains('open'))return;if(e.key==='ArrowLeft')switchSelectedRole(-1);if(e.key==='ArrowRight')switchSelectedRole(1)});renderSelectedRole();

const loginWorld=document.querySelector('#loginWorld'),loginCharacter=document.querySelector('#loginCharacter');
function openRoleLogin(){const role=selectableRoles[selectedRole],isCompany=role.name==='COMPANY';document.querySelector('#loginCharacterImage').src=role.image;document.querySelector('#loginCharacterImage').alt=`${role.name} character waving`;document.querySelector('#loginPortalLabel').textContent=`${role.name} PORTAL`;document.querySelector('#loginGreeting').innerHTML=isCompany?'HI! READY<br>TO BUILD? <b>👋</b>':'HI! READY<br>TO CREATE? <b>👋</b>';document.querySelector('#loginTitle').innerHTML=`WELCOME,<br>${role.name}.`;document.querySelector('#loginCopy').textContent=isCompany?'Sign in to create contracts, review work and fund payouts.':'Sign in to manage projects, submit work and receive local payouts.';document.querySelector('#loginSubmitText').textContent=`ENTER ${role.name} PORTAL`;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');loginWorld.classList.add('open');loginWorld.setAttribute('aria-hidden','false');loginCharacter.classList.remove('wave');void loginCharacter.offsetWidth;loginCharacter.classList.add('wave')}
document.querySelector('#continueRole').addEventListener('click',openRoleLogin);document.querySelector('#loginReturn').addEventListener('click',()=>{loginWorld.classList.remove('open');loginWorld.setAttribute('aria-hidden','true');openModal()});loginCharacter.addEventListener('click',()=>{loginCharacter.classList.remove('wave');document.querySelector('#loginGreeting').classList.remove('pop');void loginCharacter.offsetWidth;loginCharacter.classList.add('wave');document.querySelector('#loginGreeting').classList.add('pop')});document.querySelector('#showPassword').addEventListener('click',e=>{const input=document.querySelector('#loginPassword'),show=input.type==='password';input.type=show?'text':'password';e.currentTarget.textContent=show?'HIDE':'SHOW'});

// Canonical deep links used by the legacy evaluator routes. They select the
// requested human role and open the same pixel-art login experience; there is
// no second dashboard implementation.
const requestedRole=new URLSearchParams(location.search).get('role')?.toUpperCase();
if(requestedRole==='COMPANY'||requestedRole==='FREELANCER'){
  selectedRole=requestedRole==='FREELANCER'?1:0;
  renderSelectedRole();
  openRoleLogin();
}

const portalWorld=document.querySelector('#portalWorld');
document.querySelector('.portal-grid').insertAdjacentHTML('beforebegin',`<section class="agent-dex" id="agentDex"><header><div class="dex-light"><i></i></div><div><small>ANCHOR AGENT DEX</small><strong>YOUR DEAL CREW</strong></div><span id="dexCount">01 / 05</span></header><div class="dex-body"><div class="dex-display"><div class="dex-scan"></div><div class="dex-sprite dex-sprite-0" id="dexSprite"></div><span id="dexAgentState">● ACTIVE</span></div><div class="dex-info"><div class="dex-name"><small id="dexAgentNumber">AGENT 01 · CONTRACT</small><h2 id="dexAgentName">AGREEMENT SCRIBE</h2><span id="dexAgentType">TYPE / TERMS</span></div><p id="dexAgentCopy">Turns the accepted project into clear scope, milestones and approval conditions for both sides.</p><div class="dex-role-note"><small id="dexRoleLabel">FOR YOUR COMPANY</small><p id="dexRoleCopy">Prepares the work agreement for your review before anything is funded.</p></div><div class="dex-controls"><button id="dexPrev" aria-label="Previous agent">◀</button><div id="dexDots"><button class="active" data-dex="0">01</button><button data-dex="1">02</button><button data-dex="2">03</button><button data-dex="3">04</button><button data-dex="4">05</button></div><button id="dexNext" aria-label="Next agent">▶</button></div></div></div></section>`);
const portalData={COMPANY:{mode:'COMPANY COMMAND',user:'NORTHSTAR',nav:'PROJECTS',eyebrow:'COMPANY HQ / OVERVIEW',welcome:'READY TO<br>MOVE WORK?',copy:'Create a project, approve a milestone or check your next cross-border payout.',primary:'CREATE NEW PROJECT',stats:[['ACTIVE PROJECTS','06','2 awaiting review'],['IN ESCROW','€12,400','Across 4 milestones'],['PAID THIS MONTH','€28,650','11 completed payouts']],mission:['BRAND SYSTEM · MILESTONE 02','AWAITING REVIEW','COMPANY · POLAND','NORTHSTAR','FREELANCER · INDIA','ARJUN STUDIO','MILESTONE VALUE','€4,800.00','REVIEW WORK'],quick:[['NEW PROJECT','Start a global contract'],['REVIEW WORK','2 submissions waiting'],['PAYMENTS','View escrow and payouts']],activity:[['✓','WORK SUBMITTED','Brand system · 12 min ago'],['₹','ESCROW FUNDED','€4,800 · Yesterday'],['⌁','CONTRACT SIGNED','Both parties verified']]},FREELANCER:{mode:'FREELANCER COMMAND',user:'ARJUN STUDIO',nav:'MY WORK',eyebrow:'FREELANCER HQ / OVERVIEW',welcome:'READY TO<br>SHIP WORK?',copy:'Manage active projects, submit deliverables and track your next local payout.',primary:'FIND NEW PROJECT',stats:[['ACTIVE CONTRACTS','04','1 due this week'],['IN ESCROW','₹892K','Secured for your work'],['EARNED THIS MONTH','₹433K','2 completed payouts']],mission:['BRAND SYSTEM · MILESTONE 02','READY TO SUBMIT','FREELANCER · INDIA','ARJUN STUDIO','COMPANY · POLAND','NORTHSTAR','EXPECTED PAYOUT','₹433,846','SUBMIT WORK'],quick:[['FIND PROJECT','Browse verified work'],['SUBMIT WORK','1 milestone ready'],['PAYOUTS','Track incoming INR']],activity:[['✓','MILESTONE READY','Brand system · just now'],['₹','PAYOUT RECEIVED','₹186,240 · Yesterday'],['⌁','APPLICATION ACCEPTED','Identity verified']]}};
const dealAgents=[
 {number:'AGENT 01 · CONTRACT',name:'AGREEMENT SCRIBE',type:'TYPE / TERMS',copy:'Turns the accepted project into clear scope, milestones and approval conditions for both sides.',company:'Prepares the work agreement for your review before anything is funded.',freelancer:'Makes your scope, deadline and acceptance conditions clear before you begin.'},
 {number:'AGENT 02 · COMPLIANCE',name:'CORRIDOR GUARD',type:'TYPE / RULES',copy:'Checks identity credentials, corridor policy and required documents without exposing personal data.',company:'Confirms the Poland → India route and provider requirements for your payment.',freelancer:'Checks that your verified identity and destination payout route are ready.'},
 {number:'AGENT 03 · EVIDENCE',name:'PROOF KEEPER',type:'TYPE / WORK',copy:'Hashes each private deliverable and records its version, time and buyer decision on Fabric.',company:'Gives you a verifiable link between the file you review and the approval you make.',freelancer:'Protects proof of what you submitted while keeping your actual work file private.'},
 {number:'AGENT 04 · ESCROW',name:'ESCROW KEEPER',type:'TYPE / FUNDS',copy:'Locks provider settlement funds and releases them only after approved work evidence is verified.',company:'Shows that the milestone is secured before work proceeds—without a user crypto wallet.',freelancer:'Shows that provider funds are secured for your approved milestone.'},
 {number:'AGENT 05 · PAYOUT',name:'PAYOUT COURIER',type:'TYPE / FIAT',copy:'Coordinates provider settlement, reconciliation and the final simulated local-currency credit.',company:'Connects your PLN funding to a traceable completion receipt.',freelancer:'Tracks the final INR credit into your local Anchor balance.'}
];let dexIndex=0;
function renderAgentDex(index=dexIndex){dexIndex=(index+dealAgents.length)%dealAgents.length;const agent=dealAgents[dexIndex],dex=document.querySelector('#agentDex'),sprite=document.querySelector('#dexSprite'),company=selectableRoles[selectedRole].name==='COMPANY';dex.classList.add('switching');setTimeout(()=>{sprite.className=`dex-sprite dex-sprite-${dexIndex}`;setText('dexCount',`0${dexIndex+1} / 05`);setText('dexAgentNumber',agent.number);setText('dexAgentName',agent.name);setText('dexAgentType',agent.type);setText('dexAgentCopy',agent.copy);setText('dexRoleLabel',company?'FOR YOUR COMPANY':'FOR YOU AS FREELANCER');setText('dexRoleCopy',company?agent.company:agent.freelancer);document.querySelectorAll('[data-dex]').forEach((button,i)=>button.classList.toggle('active',i===dexIndex));dex.classList.remove('switching')},170)}
function setText(id,value){const element=document.querySelector(`#${id}`);if(element)element.textContent=value}
// Pure DOM update: no side effects, so hydrateRealPortalData() can call this a
// second time (once real API data lands) without re-triggering the wallet
// animation or agent carousel that renderPortal() below also kicks off.
function applyOverview(d,role,other){setText('portalMode',d.mode);setText('portalUserName',d.user);setText('portalNavRole',role.name);document.querySelector('#portalAvatar').src=role.image;document.querySelector('#portalNavCharacter').src=role.image;setText('portalEyebrow',d.eyebrow);document.querySelector('#portalWelcome').innerHTML=d.welcome;setText('portalWelcomeCopy',d.copy);document.querySelector('#portalPrimary span').textContent=d.primary;['One','Two','Three'].forEach((word,i)=>{setText(`stat${word}Label`,d.stats[i][0]);setText(`stat${word}Value`,d.stats[i][1]);setText(`stat${word}Note`,d.stats[i][2])});setText('missionTitle',d.mission[0]);setText('missionStatus',d.mission[1]);setText('missionSelfRole',d.mission[2]);setText('missionSelfName',d.mission[3]);setText('missionOtherRole',d.mission[4]);setText('missionOtherName',d.mission[5]);setText('missionAmountLabel',d.mission[6]);setText('missionAmount',d.mission[7]);document.querySelector('#missionAction').innerHTML=`${d.mission[8]} <b>→</b>`;document.querySelector('#missionSelfImage').src=role.image;document.querySelector('#missionOtherImage').src=other.image;['quickOne','quickTwo','quickThree'].forEach((id,i)=>{const button=document.querySelector(`#${id}`);button.querySelector('b').textContent=d.quick[i][0];button.querySelector('small').textContent=d.quick[i][1]});document.querySelector('#activityFeed').innerHTML=d.activity.map(x=>`<p><i>${x[0]}</i><span><b>${x[1]}</b><small>${x[2]}</small></span></p>`).join('');if(d.mission[1]==='COMPLETED'){const steps=document.querySelectorAll('.mission-progress span');steps.forEach(s=>s.classList.remove('current'));if(steps[4])steps[4].classList.add('current');const bar=document.querySelector('.mission-progress>i>b');if(bar)bar.style.width='100%'}}
// Real demo data, fetched same-origin from serve.mjs's API proxy. Runs after
// the mock render above so the portal is never empty while this is in
// flight, and fails silently (mock stays on screen) if the API is down.
let realPortals=null;
async function hydrateRealPortalData(roleName){
  if(!window.OptiWorkPortalData)return;
  if(!realPortals)realPortals=await window.OptiWorkPortalData.hydrate();
  if(!realPortals)return;
  const real=realPortals[roleName];
  if(!real)return;
  if(selectableRoles[selectedRole].name!==roleName)return;
  const role=selectableRoles[selectedRole],other=selectableRoles[role.name==='COMPANY'?1:0];
  applyOverview(real,role,other);
  renderLedgerView(realPortals.ledger);
}
// Called by workflow-ui.js after a run: that run wrote a new job, contract and
// payout, so the cached state the Home and Audit views were built from is stale.
window.refreshPortalAfterWorkflow=async function(){
  realPortals=null;
  await hydrateRealPortalData(selectableRoles[selectedRole].name);
};
function renderPortal(){const role=selectableRoles[selectedRole],d=portalData[role.name],company=role.name==='COMPANY',other=selectableRoles[company?1:0];applyOverview(d,role,other);renderSimplifiedPortal(company);resetWalletConnection();renderAgentDex(0);hydrateRealPortalData(role.name)}
function renderSimplifiedPortal(company){setText('walletLargeBalance',company?'48,200.00 PLN':'₹892,460.00');setText('walletAvailable',company?'AVAILABLE TO FUND WORK':'AVAILABLE INR BALANCE');setText('walletProvider',company?'POLAND DEMO RAIL':'INDIA DEMO RAIL');setText('workEyebrow',company?'COMPANY / CREATE NEW WORK':'FREELANCER / SUBMIT NEW WORK');document.querySelector('#workTitle').innerHTML=company?'CREATE A<br>WORK BRIEF.':'SUBMIT YOUR<br>WORK.';setText('workIntro',company?'Add the scope, budget and delivery details your freelancer needs.':'Upload the completed milestone and explain what you delivered.');setText('coreDetailsTitle',company?'WHAT NEEDS TO BE DONE?':'WHAT DID YOU COMPLETE?');setText('workNameLabel',company?'PROJECT TITLE':'MILESTONE TITLE');document.querySelector('#workName').placeholder=company?'e.g. Brand identity system':'e.g. Brand system · Milestone 02';setText('workDescriptionLabel',company?'WORK DESCRIPTION':'DELIVERY NOTES');document.querySelector('#workDescription').placeholder=company?'Describe the scope, outcomes and acceptance criteria':'Describe the completed work and anything the company should review';setText('workCategoryLabel',company?'CATEGORY':'DELIVERABLE TYPE');setText('termsTitle',company?'SET THE WORK TERMS':'ATTACH THE DELIVERABLE');setText('budgetLabel',company?'BUDGET · PLN':'EXPECTED PAYOUT · INR');document.querySelector('#budgetInput').value=company?'19800':'433846';setText('confirmText',company?'I confirm this brief contains no sensitive identity documents.':'I confirm this is the final deliverable for the selected milestone.');setText('workSubmitText',company?'CREATE WORK + CONTINUE':'SUBMIT WORK EVIDENCE');setText('dealRoleAction',company?'REVIEW SUBMITTED WORK →':'VIEW SUBMISSION PROOF →');setText('dealCurrentTitle',company?'WORK SUBMITTED':'EVIDENCE RECORDED');setText('dealCurrentCopy',company?'Private deliverable uploaded. Evidence fingerprint ready for review.':'Your deliverable remains private and its evidence fingerprint is recorded.')}
function openPortal(){renderPortal();loginWorld.classList.remove('open');loginWorld.setAttribute('aria-hidden','true');portalWorld.classList.add('open');portalWorld.setAttribute('aria-hidden','false');window.OptiWorkWorkflow?.setRole(selectableRoles[selectedRole].name);window.OptiWorkWorkflow?.init()}
document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const button=e.currentTarget.querySelector('.login-submit');button.querySelector('span').textContent='ENTERING PORTAL...';document.querySelector('#loginStatus').innerHTML='<i></i> VERIFYING DEMO IDENTITY';setTimeout(()=>{button.querySelector('span').textContent='ACCESS GRANTED ✓';document.querySelector('#loginStatus').innerHTML='<i></i> PLAYER VERIFIED';setTimeout(openPortal,450)},850)});
document.querySelector('#portalLogout').addEventListener('click',()=>{portalWorld.classList.remove('open');portalWorld.setAttribute('aria-hidden','true');scrollTo(0,0)});const portalHome=document.querySelector('#portalHome'),portalWork=document.querySelector('#portalWork'),portalDeal=document.querySelector('#portalDeal'),portalLedger=document.querySelector('#portalLedger'),portalWorkflow=document.querySelector('#portalWorkflow'),portalPlaceholder=document.querySelector('#portalPlaceholder');document.querySelectorAll('[data-portal-nav]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-portal-nav]').forEach(x=>x.classList.toggle('active',x===button));[portalHome,portalWork,portalDeal,portalLedger,portalWorkflow,portalPlaceholder].forEach(view=>view.classList.remove('active'));({home:portalHome,work:portalWork,deal:portalDeal,audit:portalLedger,workflow:portalWorkflow}[button.dataset.portalNav]||portalPlaceholder).classList.add('active');if(button.dataset.portalNav==='workflow')window.OptiWorkWorkflow?.init();document.querySelector('.portal-main').scrollTo(0,0)}));document.querySelector('#placeholderBack').addEventListener('click',()=>document.querySelector('[data-portal-nav="home"]').click());document.querySelector('#portalPrimary').addEventListener('click',()=>document.querySelector('[data-portal-nav="work"]').click());document.querySelector('#missionAction').addEventListener('click',()=>document.querySelector('[data-portal-nav="deal"]').click());
// Ledger/audit view: real books, compliance decisions and the full event
// trail for the active contract, reusing the same .portal-stats/.activity-feed
// components the Home view already uses — same design, real data.
function renderLedgerView(ledger){
  if(!ledger||!portalLedger)return;
  ['One','Two','Three'].forEach((word,i)=>{setText(`ledgerStat${word}Label`,ledger.stats[i][0]);setText(`ledgerStat${word}Value`,ledger.stats[i][1]);setText(`ledgerStat${word}Note`,ledger.stats[i][2])});
  const booksEl=document.querySelector('#ledgerBooks');
  if(booksEl)booksEl.innerHTML=ledger.books.map(x=>`<p><i>${x[0]}</i><span><b>${x[1]}</b><small>${x[2]}</small></span></p>`).join('');
  const complianceEl=document.querySelector('#ledgerCompliance');
  if(complianceEl)complianceEl.innerHTML=ledger.compliance.map(x=>`<p><i>${x[0]}</i><span><b>${x[1]}</b><small>${x[2]}</small></span></p>`).join('');
  const timelineEl=document.querySelector('#ledgerTimeline');
  if(timelineEl)timelineEl.innerHTML=ledger.timeline.map(x=>`<p><i>${x[0]}</i><span><b>${x[1]}</b><small>${x[2]}</small></span></p>`).join('');
}
const walletPopover=document.querySelector('#walletPopover'),walletButton=document.querySelector('#walletButton'),walletConnect=document.querySelector('#walletConnect');let walletConnecting=false;
function resetWalletConnection(){walletConnecting=false;walletPopover.classList.remove('open','connecting','connected');walletButton.classList.remove('connected');setText('walletBalance','CONNECT');setText('walletConnectStatus','READY TO CONNECT LOCAL FIAT RAIL_');walletConnect.querySelector('span').textContent='CONNECT WALLET'}
walletButton.addEventListener('click',()=>walletPopover.classList.toggle('open'));document.querySelector('#walletClose').addEventListener('click',()=>walletPopover.classList.remove('open'));walletConnect.addEventListener('click',()=>{if(walletConnecting)return;walletConnecting=true;walletPopover.classList.add('connecting');walletConnect.querySelector('span').textContent='CONNECTING...';setText('walletConnectStatus','CONTACTING LOCAL BANK_');setTimeout(()=>setText('walletConnectStatus','VERIFYING PROVIDER RAIL_'),750);setTimeout(()=>setText('walletConnectStatus','SECURING WALLET SESSION_'),1500);setTimeout(()=>{walletPopover.classList.remove('connecting');walletPopover.classList.add('connected');walletButton.classList.add('connected');setText('walletConnectStatus','LOCAL WALLET CONNECTED ✓');setText('walletBalance',selectableRoles[selectedRole].name==='COMPANY'?'48,200 PLN':'₹892,460');walletConnecting=false},2250)});
document.querySelector('#workFiles').addEventListener('change',e=>setText('fileStatus',e.target.files.length?`${e.target.files.length} FILE${e.target.files.length>1?'S':''} SELECTED ✓`:'PDF, DOCX, PNG, ZIP · MAX 25 MB'));document.querySelector('#workForm').addEventListener('submit',e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;setText('workFormStatus',selectableRoles[selectedRole].name==='COMPANY'?'WORK CREATED · CONTRACT WORKFLOW READY_':'WORK SUBMITTED · EVIDENCE HASH RECORDED_');setTimeout(()=>document.querySelector('[data-portal-nav="deal"]').click(),700)});
document.querySelector('#dexPrev').addEventListener('click',()=>renderAgentDex(dexIndex-1));document.querySelector('#dexNext').addEventListener('click',()=>renderAgentDex(dexIndex+1));document.querySelectorAll('[data-dex]').forEach(button=>button.addEventListener('click',()=>renderAgentDex(+button.dataset.dex)));

const guideTours={COMPANY:[
 {step:'WELCOME / 01',title:'WELCOME BACK, NORTHSTAR!',copy:'Your company command center is live. From here you can create work, approve evidence and fund local-to-local payouts.',target:'.portal-welcome'},
 {step:'PROJECTS / 02',title:'START WITH A PROJECT.',copy:'Create the job, shortlist a verified freelancer and approve one shared contract. Anchor keeps every decision in the same workflow.',target:'#portalPrimary'},
 {step:'APPROVAL / 03',title:'REVIEW BEFORE RELEASE.',copy:'The mission board shows the latest deliverable and evidence state. Your approval is required before escrow can release.',target:'.mission-board'},
 {step:'DEAL PROCESS / 04',title:'TRACK THE WHOLE DEAL.',copy:'The deal page brings contract, evidence, approval, FX, escrow and final INR credit into one clear timeline.',target:'[data-portal-nav="deal"]'}
],FREELANCER:[
 {step:'WELCOME / 01',title:'WELCOME BACK, ARJUN!',copy:'Your freelancer command center is ready. Manage your work, submit private evidence and follow every payout from escrow to INR.',target:'.portal-welcome'},
 {step:'OPPORTUNITIES / 02',title:'FIND VERIFIED WORK.',copy:'Browse projects, apply with your verified profile and approve the final contract before starting the milestone.',target:'#portalPrimary'},
 {step:'DELIVERY / 03',title:'SUBMIT WORK PRIVATELY.',copy:'Your file remains private. Anchor records its secure fingerprint, version and submission time as verifiable work evidence.',target:'.mission-board'},
 {step:'DEAL PROCESS / 04',title:'FOLLOW YOUR INR PAYOUT.',copy:'The deal page shows your work proof, approval, secured escrow and final local INR credit in one timeline.',target:'[data-portal-nav="deal"]'}
]};
let guideIndex=0,guideTarget=null;const portalGuide=document.querySelector('#portalGuide');function clearGuideTarget(){if(guideTarget)guideTarget.classList.remove('guide-focus');guideTarget=null}function renderGuide(){clearGuideTarget();const tour=guideTours[selectableRoles[selectedRole].name],item=tour[guideIndex];setText('guideStep',item.step);setText('guideTitle',item.title);setText('guideCopy',item.copy);setText('guideCount',`0${guideIndex+1} / 0${tour.length}`);document.querySelector('#guideNext').innerHTML=guideIndex===tour.length-1?'ENTER PORTAL <b>✓</b>':'NEXT <b>▶</b>';guideTarget=document.querySelector(item.target);if(guideTarget)guideTarget.classList.add('guide-focus')}function startPortalGuide(){guideIndex=0;document.querySelector('#guideCharacter').src=selectableRoles[selectedRole].image;document.querySelector('#guideCharacter').alt=`${selectableRoles[selectedRole].name} portal guide`;portalGuide.classList.add('open');portalGuide.setAttribute('aria-hidden','false');renderGuide()}function closePortalGuide(){clearGuideTarget();portalGuide.classList.remove('open');portalGuide.setAttribute('aria-hidden','true')}document.querySelector('#guideNext').addEventListener('click',()=>{const tour=guideTours[selectableRoles[selectedRole].name];if(guideIndex>=tour.length-1){closePortalGuide();return}guideIndex++;renderGuide()});document.querySelector('#guideSkip').addEventListener('click',closePortalGuide);
